language: php

branches:
  only:
    - fixTravis
    - master
    - /^[0-9]+\.[0-9]+\.[0-9]+$/

sudo: false

addons:
  apt:
    packages:
      - parallel

php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3

env:
  - TYPO3_VERSION=^8.7
  - TYPO3_VERSION=^7.6
  - TYPO3_VERSION=^6.2

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi
  - if [ "$GITHUB_COMPOSER_AUTH" ]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi

before_script:
  - if [ "$TYPO3_VERSION" == "^6.2.0" ]; then composer require typo3/cms-composer-installers="1.2.5 as 1.1.4" --no-update; fi
  - if [ "$TRAVIS_ALLOW_FAILURE" == "false" ]; then composer require typo3/cms="$TYPO3_VERSION"; fi
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
  - >
    if [ "$TRAVIS_ALLOW_FAILURE" == "false" ]; then
      echo "Running unit tests";
      .Build/bin/phpunit;

      echo "Running php lint";
      find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
    else
      echo "skip testing";
    fi

jobs:
  fast_finish: true
  allow_failures:
    - php: 5.6
      env: TYPO3_VERSION=^8.7
    - php: 5.5
      env: TYPO3_VERSION=^8.7
    - php: 5.4
      env: TYPO3_VERSION=^8.7
    - php: 5.3
      env: TYPO3_VERSION=^8.7
    - php: 5.4
      env: TYPO3_VERSION=^7.6
    - php: 5.3
      env: TYPO3_VERSION=^7.6
    - php: 7.0
      env: TYPO3_VERSION=^6.2
    - php: 7.1
      env: TYPO3_VERSION=^6.2
  include:
    - stage: deploy to ter
      install: skip
      php: 7.1
      env: TYPO3_VERSION="^7.6"
      script:
        - >
          echo -e "TER upload...\n"
          echo "TRAVIS_PHP_VERSION $TRAVIS_PHP_VERSION"
          echo "TYPO3_VERSION $TYPO3_VERSION"
#          if [ -n "$TRAVIS_TAG" ] && [ -n "$TYPO3_ORG_USERNAME" ] && [ -n "$TYPO3_ORG_PASSWORD" ]; then
#            echo -e "Preparing upload of release ${TRAVIS_TAG} to TER\n"
#            curl -sSL https://raw.githubusercontent.com/alrra/travis-after-all/1.4.4/lib/travis-after-all.js | node
#            if [ $? -eq 0 ]; then
#              # Cleanup before we upload
#              git reset --hard HEAD && git clean -fx
#              # Upload
#              TAG_MESSAGE=`git tag -n10 -l $TRAVIS_TAG | sed 's/^[0-9.]*[ ]*//g'`
#              echo "Uploading release ${TRAVIS_TAG} to TER"
#              .Build/bin/upload . "$TYPO3_ORG_USERNAME" "$TYPO3_ORG_PASSWORD" "$TAG_MESSAGE"
#            fi;
#          fi;
