language: php

branches:
  only:
    - fixTravis
    - master
    - /^[0-9]+\.[0-9]+\.[0-9]+$/

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: TYPO3_VERSION=^8.7
    - php: 7.0
      env: TYPO3_VERSION=^8.7
    - php: 7.1
      env: TYPO3_VERSION=^7.6
    - php: 7.0
      env: TYPO3_VERSION=^7.6
    - php: 5.6
      env: TYPO3_VERSION=^7.6
    - php: 5.5
      env: TYPO3_VERSION=^7.6
    - php: 5.5
      env: TYPO3_VERSION=^6.2
    - php: 5.4
      env: TYPO3_VERSION=^6.2
    - php: 5.3
      env: TYPO3_VERSION=^6.2

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi
  - if [ "$GITHUB_COMPOSER_AUTH" ]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi

before_script:
  - if [ "$TYPO3_VERSION" == "^6.2.0" ]; then composer require typo3/cms-composer-installers="1.2.5 as 1.1.4" --no-update; fi
  - composer require typo3/cms="$TYPO3_VERSION"
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
  - >
    echo "Running unit tests";
    .Build/bin/phpunit -c .Build/vendor/typo3/cms/typo3/sysext/core/Build/UnitTests.xml Tests/Unit/
  - >
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;

jobs:
  include:
    - stage: deploy to ter
      install: skip
      php: 7.1
      script:
        - >
          echo -e "TER upload...\n"
          if [ -n "$TRAVIS_TAG" ] && [ -n "$TYPO3_ORG_USERNAME" ] && [ -n "$TYPO3_ORG_PASSWORD" ]; then
            echo -e "Preparing upload of release ${TRAVIS_TAG} to TER\n"
            curl -sSL https://raw.githubusercontent.com/alrra/travis-after-all/1.4.4/lib/travis-after-all.js | node
            if [ $? -eq 0 ]; then
              # Cleanup before we upload
              git reset --hard HEAD && git clean -fx
              # Upload
              TAG_MESSAGE=`git tag -n10 -l $TRAVIS_TAG | sed 's/^[0-9.]*[ ]*//g'`
              echo "Uploading release ${TRAVIS_TAG} to TER"
              .Build/bin/upload . "$TYPO3_ORG_USERNAME" "$TYPO3_ORG_PASSWORD" "$TAG_MESSAGE"
            fi;
          fi;
