language: php

branches:
  only:
    - fixTravis
    - master
    - /^[0-9]+\.[0-9]+\.[0-9]+$/

sudo: false

addons:
  apt:
    packages:
      - parallel

php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3

env:
  - TYPO3_VERSION=^8.7
  - TYPO3_VERSION=^7.6
  - TYPO3_VERSION=^6.2

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi
  - if [ "$GITHUB_COMPOSER_AUTH" ]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi

before_script:
  - if [ "$TYPO3_VERSION" == "^6.2.0" ]; then composer require typo3/cms-composer-installers="1.2.5 as 1.1.4" --no-update; fi
  - if [ "$TRAVIS_ALLOW_FAILURE" == "false" ]; then composer require typo3/cms="$TYPO3_VERSION"; fi
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
  - >
    if [ "$TRAVIS_ALLOW_FAILURE" == "true" ]; then echo "skip testing"; return; fi;
    echo "Running unit tests";
    .Build/bin/phpunit;

    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;

jobs:
  fast_finish: true
  allow_failures:
    - php: 5.6
      env: TYPO3_VERSION=^8.7
    - php: 5.5
      env: TYPO3_VERSION=^8.7
    - php: 5.4
      env: TYPO3_VERSION=^8.7
    - php: 5.3
      env: TYPO3_VERSION=^8.7
    - php: 5.4
      env: TYPO3_VERSION=^7.6
    - php: 5.3
      env: TYPO3_VERSION=^7.6
    - php: 7.0
      env: TYPO3_VERSION=^6.2
    - php: 7.1
      env: TYPO3_VERSION=^6.2
  include:
    - stage: deploy to ter
      install: skip
      php: 7.1
      env: TYPO3_VERSION="^7.6"
      script:
        - >
          ls -l;
          echo "${TRAVIS_TAG}";
          if [ -n "$TRAVIS_TAG" ]; then
            echo -e "Preparing upload of release ${TRAVIS_TAG} to TER\n";
            git reset --hard HEAD && git clean -fx;
            TAG_MESSAGE=`git tag -n10 -l $TRAVIS_TAG | sed 's/^[0-9.]*[ ]*//g'`;
            echo "Uploading release ${TRAVIS_TAG} to TER";
            ls -l;
            echo "$TAG_MESSAGE";
          fi;
